{{- if .Values.operator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "streamforge-operator.serviceAccountName" . }}
  labels:
    {{- include "streamforge-operator.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
{{- if .Values.defaults.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "streamforge-operator.pipelineServiceAccountName" . }}
  labels:
    {{- include "streamforge-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: pipeline
  {{- with .Values.defaults.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
