{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamforge-operator.fullname" . }}-ui-secret
  labels:
    {{- include "streamforge-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
type: Opaque
stringData:
  jwt-secret: {{ .Values.ui.jwtSecret | quote }}
{{- end }}
